// sapMetadata.ts

export const knownModules = [
  "fi",
  "co",
  "mm",
  "sd",
  "pp",
  "qm",
  "pm",
  "hr",
  "ps",
  "le",
  "ewm",
  "wm",
  "tm",
  "apo",
  "crm",
  "scm",
  "srm",
  "plm",
  "bw",
  "bo",
  "bpc",
  "grc",
  "fiori",
  "hana",
  "basis",
];

export const knownSubModules = [
  "fi-ar",
  "fi-ap",
  "fi-aa",
  "fi-gl",
  "co-pc",
  "co-pa",
  "mm-pur",
  "mm-im",
  "sd-billing",
  "sd-order-management",
  "pp-mrp",
  "hr-payroll",
  "hr-time",
  "qm-inspection",
  "pm-maintenance-planning",
  "ps-wbs",
  "le-shipping",
  "ewm-inbound",
  "ewm-outbound",
  "tm-freight-order",
  "crm-marketing",
  "scm-apo",
  "plm-engineering-change",
  "grc-access-control",
];

export const knownSystems = [
  "ecc",
  "s4hana",
  "bw",
  "bobj",
  "cloud",
  "fiori",
  "netweaver",
  "btp",
  "hana",
];

export const knownIndustries = [
  "automotive",
  "aerospace",
  "retail",
  "banking",
  "insurance",
  "utilities",
  "oil-and-gas",
  "healthcare",
  "pharmaceuticals",
  "consumer-goods",
  "manufacturing",
  "telecommunications",
  "public-sector",
  "education",
  "logistics",
  "construction",
  "chemical",
  "high-tech",
  "food-and-beverage",
  "mining",
];

export const knownRoles = [
  "functional-consultant",
  "technical-consultant",
  "solution-architect",
  "techno-functional-consultant",
  "business-analyst",
  "project-manager",
  "sap-end-user",
  "support-consultant",
  "developer",
  "integration-consultant",
  "abap-developer",
  "security-consultant",
  "data-analyst",
  "product-owner",
  "test-engineer",
  "trainer",
];
